### ISSUE TITLE
Security vulnerabilities

### ISSUE THREAD

**Issue by xeon-zolt** [yogdaan/blockchain-certification#6]
these are the 3 vulnerabilities which are used dependency of other packages and updating them can result in errors 
- [ ] we should setup a Travis CI pipeline for testing
- [ ] patch the 3 vulnerabilities
![Screenshot from 2019-09-26 18-30-24](https://user-images.githubusercontent.com/4529442/65690016-c4e61600-e08b-11e9-8d09-7aea216aea0b.png)

**Comment by thakursaurabh1998** [comment]
I am closing this issue as the work is done @xeon-zolt :)
